---
nameReference:
  - kind: ConfigMap
    version: v1
    fieldSpecs:
      - path: spec/template/spec/volumes/configMap/name
        kind: Service
        group: serving.knative.dev
namespace:
  - kind: DomainMapping
    group: serving.knative.dev
    path: spec/ref/namespace
    create: true
