---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
configurations:
  - konfig.yaml
namespace: names
resources:
  - ../base
configMapGenerator:
  - name: name-add-config
    files:
      - cfg
transformers:
  - image.yaml
